### ISSUE TITLE
Kokopelli fails to load

### ISSUE THREAD

**Issue by asterixorobelix** [mkeeter/kokopelli#20]
Hi Matt

I am having some trouble getting the Kokopelli software to run. I am running Ubuntu, specifically, the Xubuntu 16.4 flavour. 

I am following the instructions on the wiki. I have installed the dependencies as shown on the install page. I have run make in the top-level directory. When I run ./kokopelli in the terminal, I get the following error: 

nathan@NathanStasinAcer:~/Desktop/CNC/kokopelli$ ./kokopelli
[|||||||---]    importing koko.glcanvas                                         
Traceback (most recent call last):
  File "./kokopelli", line 64, in <module>
    from koko.app import App
  File "/home/nathan/Desktop/CNC/kokopelli/koko/app.py", line 22, in <module>
    from   koko.frame       import MainFrame
  File "/home/nathan/Desktop/CNC/kokopelli/koko/frame.py", line 16, in <module>
    from    koko.glcanvas  import GLCanvas
  File "/home/nathan/Desktop/CNC/kokopelli/koko/glcanvas.py", line 18, in <module>
    from OpenGL.GL      import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL.GL.VERSION.GL_1_1 import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/GL/VERSION/GL_1_1.py", line 10, in <module>
    from OpenGL import platform, constants, constant, arrays
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/__init__.py", line 19, in <module>
    from OpenGL.arrays.arraydatatype import *
  File "/usr/lib/python2.7/dist-packages/OpenGL/arrays/arraydatatype.py", line 14, in <module>
    from OpenGL_accelerate.arraydatatype import ArrayDatatype as ADT
  File "arraydatatype.pyx", line 1, in init OpenGL_accelerate.arraydatatype (src/arraydatatype.c:10964)
  File "wrapper.pyx", line 3, in init OpenGL_accelerate.wrapper (src/wrapper.c:11183)
  File "/usr/lib/python2.7/dist-packages/OpenGL/error.py", line 224, in <module>
    ErrorChecker = _ErrorChecker( platform )
  File "errorchecker.pyx", line 17, in OpenGL_accelerate.errorchecker._ErrorChecker.__init__ (src/errorchecker.c:818)
TypeError: __init__() takes at least 2 positional arguments (1 given)

Do you have any idea what the problem could be?

**Comment by mkeeter** [comment]
Nope, no idea.  The error is happening within the Python OpenGL package, so I'd get started by trying to run any PyOpenGL demo code that you can find online.
